// Schema field constants to avoid hardcoding field names
export const SCHEMA_FIELDS = {
  REVIEW: {
    AUTHOR_ID: SCHEMA_FIELDS.REVIEW.AUTHOR_ID,
    TARGET_ID: SCHEMA_FIELDS.REVIEW.TARGET_ID,
    BOOKING_ID: SCHEMA_FIELDS.REVIEW.BOOKING_ID,
    CONTRACT_ID: SCHEMA_FIELDS.REVIEW.CONTRACT_ID,
    RATING: SCHEMA_FIELDS.REVIEW.RATING,
    TEXT: SCHEMA_FIELDS.REVIEW.TEXT,
    CREATED_AT: SCHEMA_FIELDS.USER.CREATED_AT,
    MIGRATED_AT: SCHEMA_FIELDS.REVIEW.MIGRATED_AT,
    MIGRATION_VERSION: SCHEMA_FIELDS.REVIEW.MIGRATION_VERSION,
    // Legacy fields for backward compatibility
    REVIEWER_ID: 'reviewerId',
    REVIEWED_ID: 'reviewedId',
  },
  USER: {
    ID: SCHEMA_FIELDS.USER.ID,
    EMAIL: SCHEMA_FIELDS.USER.EMAIL,
    NAME: SCHEMA_FIELDS.USER.NAME,
    ROLE: SCHEMA_FIELDS.USER.ROLE,
    CREATED_AT: SCHEMA_FIELDS.USER.CREATED_AT,
    UPDATED_AT: SCHEMA_FIELDS.USER.UPDATED_AT,
    AVERAGE_RATING: SCHEMA_FIELDS.USER.AVERAGE_RATING,
    REVIEW_COUNT: SCHEMA_FIELDS.USER.REVIEW_COUNT,
    TIER: SCHEMA_FIELDS.USER.TIER,
    XP: SCHEMA_FIELDS.USER.XP,
    RANK_SCORE: SCHEMA_FIELDS.USER.RANK_SCORE,
  },
  BOOKING: {
    ID: SCHEMA_FIELDS.USER.ID,
    CLIENT_ID: SCHEMA_FIELDS.BOOKING.CLIENT_ID,
    PROVIDER_ID: SCHEMA_FIELDS.BOOKING.PROVIDER_ID,
    SERVICE_ID: SCHEMA_FIELDS.BOOKING.SERVICE_ID,
    SERVICE_NAME: SCHEMA_FIELDS.BOOKING.SERVICE_NAME,
    STATUS: SCHEMA_FIELDS.BOOKING.STATUS,
    CREATED_AT: SCHEMA_FIELDS.USER.CREATED_AT,
    UPDATED_AT: SCHEMA_FIELDS.USER.UPDATED_AT,
  },
  NOTIFICATION: {
    USER_ID: SCHEMA_FIELDS.NOTIFICATION.USER_ID,
    TYPE: SCHEMA_FIELDS.NOTIFICATION.TYPE,
    MESSAGE: SCHEMA_FIELDS.NOTIFICATION.MESSAGE,
    READ: SCHEMA_FIELDS.NOTIFICATION.READ,
  },
  SERVICE: {
    CREATOR_ID: SCHEMA_FIELDS.SERVICE.CREATOR_ID,
    DESCRIPTION: SCHEMA_FIELDS.SERVICE.DESCRIPTION,
    CATEGORY: SCHEMA_FIELDS.SERVICE.CATEGORY,
    PRICE: SCHEMA_FIELDS.SERVICE.PRICE,
    DURATION: SCHEMA_FIELDS.SERVICE.DURATION,
  },
  XP_TRANSACTION: {
    EVENT: SCHEMA_FIELDS.XP_TRANSACTION.EVENT,
    XP_AMOUNT: SCHEMA_FIELDS.XP_TRANSACTION.XP_AMOUNT,
  }
} as const;