name: GitHub Agent

on:
  issues:
    types: [opened, labeled]   # fire when issue is created *or* label is toggled

jobs:
  run-agent:
    if: contains(github.event.label.name, 'agent')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/copilot-coding-agent@v1    # <-- correct slug
        with:
          github-token: ${{ secrets.GH_AGENT_TOKEN }}
