name: Playwright E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Setup Firebase Emulators
      run: |
        npm install -g firebase-tools
        # Create test data directory if it doesn't exist
        mkdir -p ./test-data
        
    - name: Start Firebase Emulators
      run: |
        firebase emulators:start --only firestore,auth --project demo-test --export-on-exit=./test-data &
        # Wait for emulators to be ready
        sleep 20
        
    - name: Build Next.js application
      run: npm run build
      env:
        SKIP_ENV_VALIDATION: true
        NEXTAUTH_SECRET: test-secret-key-for-ci
        NEXTAUTH_URL: http://localhost:3000
        NEXT_PUBLIC_FIREBASE_API_KEY: test-api-key
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: demo-test.firebaseapp.com
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: demo-test
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: demo-test.appspot.com
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: 123456789
        NEXT_PUBLIC_FIREBASE_APP_ID: test-app-id
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: pk_test_mock_key
        STRIPE_SECRET_KEY: sk_test_mock_key
        SENDGRID_API_KEY: test-sendgrid-key
        SMTP_EMAIL: test@example.com
        SMTP_PASS: test-password
        
    - name: Start Next.js application
      run: |
        npm start &
        # Wait for the application to be ready
        sleep 15
        curl -f http://localhost:3000 || exit 1
      env:
        PORT: 3000
        SKIP_ENV_VALIDATION: true
        NEXTAUTH_SECRET: test-secret-key-for-ci
        NEXTAUTH_URL: http://localhost:3000
        NEXT_PUBLIC_FIREBASE_API_KEY: test-api-key
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: demo-test.firebaseapp.com
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: demo-test
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: demo-test.appspot.com
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: 123456789
        NEXT_PUBLIC_FIREBASE_APP_ID: test-app-id
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: pk_test_mock_key
        STRIPE_SECRET_KEY: sk_test_mock_key
        SENDGRID_API_KEY: test-sendgrid-key
        SMTP_EMAIL: test@example.com
        SMTP_PASS: test-password
        
    - name: Run Playwright tests
      run: npm run test:e2e -- --project=chromium
      env:
        CI: true
        SKIP_ENV_VALIDATION: true
        NEXTAUTH_SECRET: test-secret-key-for-ci
        NEXTAUTH_URL: http://localhost:3000
        NEXT_PUBLIC_FIREBASE_API_KEY: test-api-key
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: demo-test.firebaseapp.com
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: demo-test
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: demo-test.appspot.com
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: 123456789
        NEXT_PUBLIC_FIREBASE_APP_ID: test-app-id
        NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: pk_test_mock_key
        STRIPE_SECRET_KEY: sk_test_mock_key
        SENDGRID_API_KEY: test-sendgrid-key
        SMTP_EMAIL: test@example.com
        SMTP_PASS: test-password
        
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
        
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 30
        
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-traces
        path: test-results/*/trace.zip
        retention-days: 30
