'use client';

import { useEffect, useState } from 'react';

const steps = [
  {
    title: 'Welcome to AuditoryX!',
    description: 'This is your global creative dashboard. Here’s how to get started.',
  },
  {
    title: 'Book Creatives',
    description: 'Use the explore page to find artists, producers, or studios you can book instantly.',
  },
  {
    title: 'Manage Contracts',
    description: 'Each booking comes with an autogenerated contract — view it under your dashboard.',
  },
];

export default function WalkthroughOverlay() {
  const [active, setActive] = useState(false);
  const [step, setStep] = useState(0);

  useEffect(() => {
    const hasSeen = localStorage.getItem('walkthroughSeen');
    if (!hasSeen) {
      setActive(true);
    }
  }, []);

  const handleNext = () => {
    if (step < steps.length - 1) {
      setStep(step + 1);
    } else {
      localStorage.setItem('walkthroughSeen', 'true');
      setActive(false);
    }
  };

  const handleClose = () => {
    localStorage.setItem('walkthroughSeen', 'true');
    setActive(false);
  };

  if (!active) return null;

  return (
    <div className="fixed inset-0 bg-black bg-opacity-80 z-50 flex items-center justify-center">
      <div className="bg-white text-black p-6 rounded-lg max-w-md w-full shadow-lg relative">
        <button
          onClick={handleClose}
          className="absolute top-2 right-3 text-sm text-gray-500 hover:text-black"
        >
          ✕
        </button>

        <h2 className="text-xl font-bold mb-2">{steps[step].title}</h2>
        <p className="text-sm text-gray-700 mb-4">{steps[step].description}</p>

        <div className="flex justify-between items-center">
          <div className="text-xs text-gray-400">
            Step {step + 1} of {steps.length}
          </div>
          <button
            onClick={handleNext}
            className="bg-black text-white px-4 py-2 rounded hover:bg-gray-900 transition"
          >
            {step < steps.length - 1 ? 'Next' : 'Finish'}
          </button>
        </div>
      </div>
    </div>
  );
}
// Usage example
// import WalkthroughOverlay from './WalkthroughOverlay';
//
// function App() {
//   return (
//     <div>